/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_engine_free(a: number): void;
export function engine_new(a: number): void;
export function engine_set_size(a: number, b: number, c: number): void;
export function engine_load_tab(a: number, b: number, c: number, d: number, e: number): void;
export function engine_has_content(a: number): number;
export function engine_set_active_tab(a: number, b: number): void;
export function engine_summary(a: number, b: number): void;
export function engine_all_poster_urls(a: number, b: number): void;
export function engine_posters_to_load(a: number, b: number): void;
export function engine_evict_lru(a: number): void;
export function engine_add_poster(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function engine_add_poster_bitmap(a: number, b: number, c: number, d: number, e: number): void;
export function engine_rail_titles(a: number, b: number): void;
export function engine_append_rails(a: number, b: number, c: number, d: number): void;
export function engine_loaded_rail_count(a: number): number;
export function engine_focus_rail(a: number): number;
export function engine_scroll_busy(a: number): number;
export function engine_set_tab_count(a: number, b: number): void;
export function engine_tab_count(a: number): number;
export function engine_active_tab(a: number): number;
export function engine_featured_count(a: number): number;
export function engine_featured_backdrops(a: number, b: number): void;
export function engine_featured_title(a: number, b: number, c: number): void;
export function engine_featured_description(a: number, b: number, c: number): void;
export function engine_in_hero(a: number): number;
export function engine_select_hero(a: number): void;
export function engine_is_home(a: number): number;
export function engine_enter_meta(a: number): void;
export function engine_is_meta(a: number): number;
export function engine_is_player(a: number): number;
export function engine_enter_player(a: number): void;
export function engine_back(a: number): void;
export function engine_set_playback(a: number, b: number, c: number, d: number): void;
export function engine_focused_title(a: number, b: number): void;
export function engine_focused_description(a: number, b: number): void;
export function engine_focused_poster(a: number, b: number): void;
export function engine_focused_video(a: number, b: number): void;
export function engine_input(a: number, b: number, c: number): void;
export function engine_tick(a: number, b: number): void;
export function engine_add_text_texture(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
